name: Nix flake check

on:
  push:
  pull_request:

jobs:
  nix_flake_check:
    name: Nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: nixbuild/nix-quick-install-action@5bb6a3b3abe66fd09bbf250dce8ada94f856a703 # v30
      - run: nix --version
      - run: nix flake check
