name: Clippy check

on:
  push:
  pull_request:

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add clippy
      - run: cargo clippy --all-features
        env:
          RUSTFLAGS: "-Dwarnings"
