name: Post release
on:
  release:
    types: [published, released]
  workflow_dispatch:

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: -l 2
          commit_summary_template: "update changelog for %s changes"
          header: |
            # Changelog

            ## [Unreleased]

            - see: <https://github.com/thomask33/kube-quantity-rs/compare/v0.1.1...HEAD>
